from pathlib import Path

REQUIRED_ROOT_FILES = (
    "README.md",
    "pyproject.toml",
    "noxfile.py",
    "Makefile",
    ".gitignore",
    "configs/fedcampaign-emhi.yaml",
    "configs/tests.yml",
    "configs/smoke.yml",
    "docs/Roadmap.md",
)

REQUIRED_SOURCE_FILES = (
    "src/fedcampaign_emhi/__init__.py",
    "src/fedcampaign_emhi/domain/__init__.py",
    "src/fedcampaign_emhi/domain/enums.py",
    "src/fedcampaign_emhi/domain/types.py",
    "src/fedcampaign_emhi/config/__init__.py",
    "src/fedcampaign_emhi/config/schema.py",
    "src/fedcampaign_emhi/config/loading.py",
    "src/fedcampaign_emhi/config/validation.py",
    "src/fedcampaign_emhi/datasets/__init__.py",
    "src/fedcampaign_emhi/datasets/inventory.py",
    "src/fedcampaign_emhi/datasets/preprocessing.py",
    "src/fedcampaign_emhi/datasets/partitions.py",
    "src/fedcampaign_emhi/datasets/campaigns.py",
    "src/fedcampaign_emhi/datasets/optc/__init__.py",
    "src/fedcampaign_emhi/datasets/optc/loading.py",
    "src/fedcampaign_emhi/datasets/optc/canonicalization.py",
    "src/fedcampaign_emhi/datasets/optc/ground_truth.py",
    "src/fedcampaign_emhi/datasets/optc/validation.py",
    "src/fedcampaign_emhi/datasets/tc_engagement_5/__init__.py",
    "src/fedcampaign_emhi/datasets/tc_engagement_5/loading.py",
    "src/fedcampaign_emhi/datasets/tc_engagement_5/canonicalization.py",
    "src/fedcampaign_emhi/datasets/tc_engagement_5/ground_truth.py",
    "src/fedcampaign_emhi/datasets/tc_engagement_5/validation.py",
    "src/fedcampaign_emhi/models/__init__.py",
    "src/fedcampaign_emhi/models/isolation_forest.py",
    "src/fedcampaign_emhi/models/one_class_svm.py",
    "src/fedcampaign_emhi/models/autoencoder.py",
    "src/fedcampaign_emhi/detection/__init__.py",
    "src/fedcampaign_emhi/detection/detector_assignment.py",
    "src/fedcampaign_emhi/detection/fitting.py",
    "src/fedcampaign_emhi/detection/scoring.py",
    "src/fedcampaign_emhi/detection/local_policy.py",
    "src/fedcampaign_emhi/emhi/__init__.py",
    "src/fedcampaign_emhi/emhi/coalitions.py",
    "src/fedcampaign_emhi/emhi/ranks.py",
    "src/fedcampaign_emhi/emhi/contexts.py",
    "src/fedcampaign_emhi/emhi/basis.py",
    "src/fedcampaign_emhi/emhi/projection.py",
    "src/fedcampaign_emhi/emhi/innovations.py",
    "src/fedcampaign_emhi/emhi/innovation_calibration.py",
    "src/fedcampaign_emhi/emhi/evidence.py",
    "src/fedcampaign_emhi/emhi/thresholds.py",
    "src/fedcampaign_emhi/emhi/sequential.py",
    "src/fedcampaign_emhi/comparators/__init__.py",
    "src/fedcampaign_emhi/comparators/rank_fusion.py",
    "src/fedcampaign_emhi/comparators/conditional_hofd.py",
    "src/fedcampaign_emhi/comparators/pair_dependence.py",
    "src/fedcampaign_emhi/comparators/lancaster.py",
    "src/fedcampaign_emhi/comparators/connected_information.py",
    "src/fedcampaign_emhi/comparators/conditional_log_linear.py",
    "src/fedcampaign_emhi/comparators/d_vine.py",
    "src/fedcampaign_emhi/comparators/global_factor_residual.py",
    "src/fedcampaign_emhi/comparators/multistream_cusum.py",
    "src/fedcampaign_emhi/comparators/fedavg_autoencoder.py",
    "src/fedcampaign_emhi/comparators/composition.py",
    "src/fedcampaign_emhi/synthetic/__init__.py",
    "src/fedcampaign_emhi/synthetic/common_mode.py",
    "src/fedcampaign_emhi/synthetic/controlled_campaigns.py",
    "src/fedcampaign_emhi/synthetic/self_explanation.py",
    "src/fedcampaign_emhi/synthetic/pure_order.py",
    "src/fedcampaign_emhi/synthetic/robustness.py",
    "src/fedcampaign_emhi/synthetic/context_boundaries.py",
    "src/fedcampaign_emhi/synthetic/validation.py",
    "src/fedcampaign_emhi/experiments/__init__.py",
    "src/fedcampaign_emhi/experiments/definitions.py",
    "src/fedcampaign_emhi/experiments/coordinates.py",
    "src/fedcampaign_emhi/experiments/validation.py",
    "src/fedcampaign_emhi/evaluation/__init__.py",
    "src/fedcampaign_emhi/evaluation/records.py",
    "src/fedcampaign_emhi/evaluation/campaign_replay.py",
    "src/fedcampaign_emhi/evaluation/benign_horizons.py",
    "src/fedcampaign_emhi/evaluation/metrics.py",
    "src/fedcampaign_emhi/evaluation/scalability.py",
    "src/fedcampaign_emhi/evaluation/validation.py",
    "src/fedcampaign_emhi/analysis/__init__.py",
    "src/fedcampaign_emhi/analysis/summaries.py",
    "src/fedcampaign_emhi/analysis/statistics.py",
    "src/fedcampaign_emhi/analysis/multiplicity.py",
    "src/fedcampaign_emhi/analysis/claims.py",
    "src/fedcampaign_emhi/artifacts/__init__.py",
    "src/fedcampaign_emhi/artifacts/paths.py",
    "src/fedcampaign_emhi/artifacts/records.py",
    "src/fedcampaign_emhi/artifacts/storage.py",
    "src/fedcampaign_emhi/artifacts/provenance.py",
    "src/fedcampaign_emhi/artifacts/dependencies.py",
    "src/fedcampaign_emhi/artifacts/validation.py",
    "src/fedcampaign_emhi/execution/__init__.py",
    "src/fedcampaign_emhi/execution/planning.py",
    "src/fedcampaign_emhi/execution/runner.py",
    "src/fedcampaign_emhi/execution/recovery.py",
    "src/fedcampaign_emhi/execution/status.py",
    "src/fedcampaign_emhi/runtime/__init__.py",
    "src/fedcampaign_emhi/runtime/determinism.py",
    "src/fedcampaign_emhi/runtime/monitoring.py",
    "src/fedcampaign_emhi/runtime/logging.py",
    "src/fedcampaign_emhi/reporting/__init__.py",
    "src/fedcampaign_emhi/reporting/evidence.py",
    "src/fedcampaign_emhi/reporting/tables.py",
    "src/fedcampaign_emhi/reporting/figures.py",
    "src/fedcampaign_emhi/reporting/reproducibility.py",
    "src/fedcampaign_emhi/cli/__init__.py",
    "src/fedcampaign_emhi/cli/main.py",
    "src/fedcampaign_emhi/cli/commands/__init__.py",
    "src/fedcampaign_emhi/cli/commands/doctor.py",
    "src/fedcampaign_emhi/cli/commands/preprocess.py",
    "src/fedcampaign_emhi/cli/commands/plan.py",
    "src/fedcampaign_emhi/cli/commands/smoke.py",
    "src/fedcampaign_emhi/cli/commands/run.py",
    "src/fedcampaign_emhi/cli/commands/status.py",
    "src/fedcampaign_emhi/cli/commands/report.py",
)

REQUIRED_TEST_FILES = (
    "tests/conftest.py",
    "tests/architecture/test_dependency_boundaries.py",
    "tests/architecture/test_public_type_boundaries.py",
    "tests/architecture/test_no_any_dict_object.py",
    "tests/architecture/test_no_primitive_leaks.py",
    "tests/architecture/test_no_hardcoded_values.py",
    "tests/architecture/test_configuration_ownership.py",
    "tests/architecture/test_no_duplicate_constants.py",
    "tests/architecture/test_dead_code.py",
    "tests/architecture/test_enum_integrity.py",
    "tests/architecture/test_no_test_only_production_code.py",
    "tests/architecture/test_no_redirects_shims_reexports.py",
    "tests/architecture/test_naming_policy.py",
    "tests/architecture/test_canonical_vocabulary.py",
    "tests/architecture/test_no_comments_or_docstrings.py",
    "tests/architecture/test_no_todos_or_temporary_code.py",
    "tests/architecture/test_static_typing.py",
    "tests/architecture/test_code_quality.py",
    "tests/architecture/test_dependency_hygiene.py",
    "tests/scientific/test_data_invariants.py",
    "tests/scientific/test_emii_exclusion_invariants.py",
    "tests/scientific/test_pure_order_invariants.py",
    "tests/scientific/test_projection_and_crossfit_invariants.py",
    "tests/scientific/test_sequential_evidence_contracts.py",
    "tests/scientific/test_odi_and_campaign_contracts.py",
    "tests/scientific/test_experiment_contracts.py",
    "tests/scientific/test_claim_conditions.py",
    "tests/integration/preprocessing/test_optc_pipeline.py",
    "tests/integration/preprocessing/test_tc_engagement_5_pipeline.py",
    "tests/integration/detection/test_detector_score_policy_pipeline.py",
    "tests/integration/scientific_pipeline/test_emhi_fit_calibrate_evaluate.py",
    "tests/integration/scientific_pipeline/test_comparator_pipeline.py",
    "tests/integration/scientific_pipeline/test_synthetic_validation_pipeline.py",
    "tests/integration/execution/test_artifact_reuse.py",
    "tests/integration/execution/test_selective_invalidation.py",
    "tests/integration/execution/test_checkpoint_recovery.py",
    "tests/integration/reporting/test_verified_evidence_materialization.py",
    "tests/integration/cli/test_command_ownership.py",
    "tests/e2e/test_preprocess_plan_smoke.py",
    "tests/e2e/test_run_status_report.py",
    "tests/e2e/test_reuse_recovery_and_overwrite.py",
    "tests/e2e/test_confirmatory_execution.py",
    "tests/smoke/test_smoke.py",
)

REQUIRED_TEST_DIRECTORIES = (
    "tests/unit/domain",
    "tests/unit/config",
    "tests/unit/datasets",
    "tests/unit/datasets/optc",
    "tests/unit/datasets/tc_engagement_5",
    "tests/unit/models",
    "tests/unit/detection",
    "tests/unit/emhi",
    "tests/unit/comparators",
    "tests/unit/synthetic",
    "tests/unit/experiments",
    "tests/unit/evaluation",
    "tests/unit/analysis",
    "tests/unit/artifacts",
    "tests/unit/execution",
    "tests/unit/runtime",
    "tests/unit/reporting",
    "tests/unit/cli",
)


def test_canonical_repository_files_exist(repo_root: Path) -> None:
    missing = [
        relative
        for relative in (*REQUIRED_ROOT_FILES, *REQUIRED_SOURCE_FILES, *REQUIRED_TEST_FILES)
        if not (repo_root / relative).is_file()
    ]
    assert missing == []


def test_canonical_test_directories_exist(repo_root: Path) -> None:
    missing = [
        relative for relative in REQUIRED_TEST_DIRECTORIES if not (repo_root / relative).is_dir()
    ]
    assert missing == []


def test_data_raw_is_external_symlink(repo_root: Path) -> None:
    raw = repo_root / "data" / "raw"
    assert raw.is_symlink()
    checksums = repo_root / "data" / "external_checksums"
    assert checksums.is_dir()
